### ISSUE TITLE
Wrong folder scanned for group/host_vars

### ISSUE THREAD

**Issue by nymous** [fboender/ansible-cmdb#137]
At these lines https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/ansible.py#L126 and https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/ansible.py#L177, the path shown in the debug message doesn't match the one used for the rest of the method.

This leads to inconsistent behavior: if I pass an inventory without a trailing slash (eg. `-i /home/user/inventories/inventory-prod`), it logs "Parsing host vars (dir): /home/user/inventories/inventory-prod/group_vars", but the `path` is `/home/user/inventories/group_vars`.

I tried a quick fix, changing these lines to something like
```python
path = os.path.join(inventory_path, 'group_vars')
self.log.debug("Parsing group vars (dir): {0}".format(path))
```
fixes the issue, while also not doing the "almost same but wrong sometimes" calculation in debug print and in variable affectation.

**Comment by fboender** [comment]
I've fixed the logging. Thanks!

**Comment by nymous** [comment]
With this fix the path printed and the path used are the same, but the bug is still there.

Because you you use `os.path.dirname()` when joining paths, it removes the last part of the given inventory folder if it does not end with a `/`.

so `ansible-cmdb -i inventories/inventory-prod` gives
```python
os.path.dirname(inventory_path) # inventories
os.path.join(os.path.dirname(inventory_path), 'group_vars') # inventories/group_vars
```
whereas `ansible-cmdb -i inventories/inventory-prod/` gives
```python
os.path.dirname(inventory_path) # inventories/inventory-prod
os.path.join(os.path.dirname(inventory_path), 'group_vars') # inventories/inventory-prod/group_vars
```

I'm guessing that because I send an argument without a trailing slash, it is handled as if it were a file, but I don't know how to fix it correctly. Maybe just being explicit in the readme that passing a directory requires the final `/`...

**Comment by fboender** [comment]
The `-i` switch is supposed to point to the inventory file (e.g. `hosts`). Ansible-cmdb then scans the directory that the `hosts` file is in for `group_vars` and `host_vars`. The normal way to invoke it would be `ansible-cmdb -i inventories/inventory-prod/hosts`. Since there are so many different ways to put together the inventory, I'm not sure if you have a `hosts` file at all? 

Could you give some more details about the way your `inventories` directory structure looks like? Technically there's no reason it should even be required to specify a path to the `hosts` file, since ansible-cmdb now scans the entire dir. I'm just not sure if I can implement a fix that will be backwards compatible.

**Comment by nymous** [comment]
The directory structure looks like this:
```
inventories/
  inventory-prod/
    client1/
      hosts
    client2/
      hosts
  inventory-dev/
    client1/
      hosts
```

As you said, I do not have a `hosts` file in the root folder.

Maybe a way to fix it would be to check if the given inventory is a folder, and if it doesn't have a trailing slash to add one to the path... I'm not sure if it would be a clean solution though.

**Comment by fboender** [comment]
> Maybe a way to fix it would be to check if the given inventory is a folder, and if it doesn't have a trailing slash to add one to the path... I'm not sure if it would be a clean solution though.

That's basically the right solution, yes. I'm now detecting whether the inventory points to a file or dir. If it points to a dir, I don't use `dirname()`, as it strips off the last part of the path, which we don't want.

I was confusing myself with regards to the way your inventory is built up. I expected ansible-cmdb to look for `host_vars` and `group_vars` in `inventories/inventory_prod/clients1/host_vars`. As in, relative to the `hosts` file. But ansible-cmdb recursively scans for files when given a directory as the argument to `-i`. This is why it's finding your `hosts` file. Just as a precautionary remark: if you have `host_vars` or `group_vars` at `inventory-prod/client1/host_vars`, ansible-cmdb will *not* detect those.

I've pushed a fix to the master branch that now properly determines the path to `host_vars` and `group_vars`. I've also added some additional debugging information:

```
ansible-cmdb -d -i ~/Temp/inventory-prod example/out
Parsing host vars (dir): /home/fboender/Temp/inventory-prod/host_vars
No such dir /home/fboender/Temp/inventory-prod/host_vars
Parsing group vars (dir): /home/fboender/Temp/inventory-prod/group_vars
No such dir /home/fboender/Temp/inventory-prod/group_vars
```

and

```
ansible-cmdb -d -i ~/Temp/inventory-prod example/out
Parsing host vars (dir): /home/fboender/Temp/inventory-prod/host_vars
No such dir /home/fboender/Temp/inventory-prod/host_vars
Parsing group vars (dir): /home/fboender/Temp/inventory-prod/group_vars
No such dir /home/fboender/Temp/inventory-prod/group_vars
```

I'm assuming btw that hosts found in, for example, `inventory-dev/clients1/hosts` are not treated specially by Ansible? As in, they don't belong to a group called `clients1` or `inventory-dev` or anything? This is just a convenient method for you to group your hosts?

Thank you for your bug report! I hope everything is as it should be now. If not, don't hesitate to reopen the bug and let me know!

**Comment by fboender** [comment]
Sorry, the command for the second example should include a backslash, like this:

```
ansible-cmdb -d -i ~/Temp/inventory-prod/ example/out
```

**Comment by nymous** [comment]
That commit 7bad79cdb13cfc4532a18d47974551a2b70f4039 looks perfect to me! Thanks!

And for the record:
>I'm assuming btw that hosts found in, for example, inventory-dev/clients1/hosts are not treated specially by Ansible? As in, they don't belong to a group called clients1 or inventory-dev or anything? This is just a convenient method for you to group your hosts?

No they're not, it's just a way for us to organize the hosts but they don't get 'magic' groups or anything.
